close all;
clear;

load("regularityTest.mat");

% nn_bin_def = 10 ; % microns
% nn_max_def = 100 ; % microns
% vv_bin_def = 10e2 ; % microns^2
% vv_max_def = 10e3 ; % microns^2
% er_bin_def = 10 ; % microns
% er_max_def = 100 ; % microns

% sparse_threshold = 1.2;
% [cells, roi, rfs] = simulateMosaic();
% [voronoi, triangles, valid_mosaic] = computeSparseVoronoi(cells, roi, 'Sparseness_Threshold', sparse_threshold);
% ci  = OptimizeCoverageSize(rfs, roi, 'Valid_RFs', valid_mosaic, 'Voronoi', voronoi);

% [nnri, vvri, er] = computeRegularityIndices(cells, roi, voronoi, ...
%                                             'Valid_Cells', valid_mosaic, ...
%                                             'NN_Bin', nn_bin_def, ...
%                                             'NN_Max', nn_max_def, ...
%                                             'VV_Bin' , vv_bin_def, ...
%                                             'VV_Max' , vv_max_def, ...
%                                             'ER_Bin' , er_bin_def, ...
%                                             'ER_Max' , er_max_def);
% save("regularityTest.mat");


% plotRFCoverage(ci);

showMosaicRegularity(cells, roi, ...
    'Voronoi_Cells', valid_mosaic, ...
    'RFs', rfs, ...
    'Voronoi', voronoi, ...
    'NNRI', nnri, ...
    'VVRI', vvri, ...
    'ER', er);

