function [H, H_inv] = buildH(t_pre, r, s, t_post)

H_pre_translation = [   1, 0, t_pre(1); ...
                        0, 1, t_pre(2); ...
                        0, 0, 1];
         
H_rotation = [          +cos(r), -sin(r), 0; ...
                        +sin(r), +cos(r), 0; ...
                        0,       0,       1];
  
H_scaling = [           s, 0, 0; ...
                        0, s, 0; ...
                        0, 0, 1];

H_post_translation = [  1, 0, t_post(1); ...
                        0, 1, t_post(2); ...
                        0, 0, 1];

H = H_post_translation * H_scaling * H_rotation * H_pre_translation;
H_inv = inv(H);
