clear
close all

exp_id = '20210302_reachr2';
dataset_id = '20210302_reachr2_noSTAs';
mea_rate = 20000;
on_cell_id = 45;
off_cell_id = 2;
off_leak_cell_id = 77;

psth_pattern = 'flicker';
activation_labels = {'on', 'off'};

psth_label_visual = 'simple';
psth_label_opto = 'lap4_acet_30nd100p';
psth_label_control = 'lap4_acet_cnqxcpp_30nd100p';


color_on = [1, 0, 0; 1, 0, 0];
color_off = [0, 0, 1; 0, 0, 1];

x_lims = [-0.5, 2.5];
up_bound = 80;

changeDataset(dataset_id);
load(getDatasetMat(), 'psths', 'activations', 'cellsTable');


subplot(3, 3, 1);
title('ON Cell (visual response)');
plotActivations(on_cell_id, psth_pattern, psth_label_visual, activation_labels, ...
    'Show_Stimulus', 'blocks', ...
    'Show_Stimulus_Block_As_Luminance', true, ...
    'Upper_Bound', up_bound, ...
    'Show_Legend', false, ...
    'PSTHS', psths, ...
    'ACTIVATIONS', activations, ...
    'Colors_Active_One', color_on);
xlim(x_lims)

subplot(3, 3, 4);
title('ON Cell (optogenetic response)');
plotActivations(on_cell_id, psth_pattern, psth_label_opto, activation_labels, ...
    'Show_Stimulus', 'blocks', ...
    'Show_Stimulus_Block_As_Luminance', true, ...
    'Upper_Bound', up_bound, ...
    'Show_Legend', false, ...
    'PSTHS', psths, ...
    'ACTIVATIONS', activations, ...
    'Colors_Active_One', color_on);
xlim(x_lims)

subplot(3, 3, 7);
title('ON Cell (control response)');
plotActivations(on_cell_id, psth_pattern, psth_label_control, activation_labels, ...
    'Show_Stimulus', 'blocks', ...
    'Show_Stimulus_Block_As_Luminance', true, ...
    'Upper_Bound', up_bound, ...
    'Show_Legend', false, ...
    'PSTHS', psths, ...
    'ACTIVATIONS', activations, ...
    'Colors_Active_One', color_on);
xlim(x_lims)


subplot(3, 3, 2);
title('OFF Cell (visual response)');
plotActivations(off_cell_id, psth_pattern, psth_label_visual, activation_labels, ...
    'Show_Stimulus', 'blocks', ...
    'Show_Stimulus_Block_As_Luminance', true, ...
    'Upper_Bound', up_bound, ...
    'Show_Legend', false, ...
    'PSTHS', psths, ...
    'ACTIVATIONS', activations, ...
    'Colors_Active_One', color_off);
xlim(x_lims)


subplot(3, 3, 5);
title('OFF Cell (optogenetic response)');
plotActivations(off_cell_id, psth_pattern, psth_label_opto, activation_labels, ...
    'Show_Stimulus', 'blocks', ...
    'Show_Stimulus_Block_As_Luminance', true, ...
    'Upper_Bound', up_bound, ...
    'Show_Legend', false, ...
    'PSTHS', psths, ...
    'ACTIVATIONS', activations, ...
    'Colors_Active_One', color_off);
xlim(x_lims)

subplot(3, 3, 8);
title('OFF Cell (control response)');
plotActivations(off_cell_id, psth_pattern, psth_label_control, activation_labels, ...
    'Show_Stimulus', 'blocks', ...
    'Show_Stimulus_Block_As_Luminance', true, ...
    'Upper_Bound', up_bound, ...
    'Show_Legend', false, ...
    'PSTHS', psths, ...
    'ACTIVATIONS', activations, ...
    'Colors_Active_One', color_off);
xlim(x_lims)


subplot(3, 3, 3);
title('OFF Cell (visual response)');
plotActivations(off_leak_cell_id, psth_pattern, psth_label_visual, activation_labels, ...
    'Show_Stimulus', 'blocks', ...
    'Show_Stimulus_Block_As_Luminance', true, ...
    'Upper_Bound', up_bound, ...
    'Show_Legend', false, ...
    'PSTHS', psths, ...off_cell_id
    'ACTIVATIONS', activations, ...
    'Colors_Active_One', color_off);
xlim(x_lims)


subplot(3, 3, 6);
title('OFF Cell (optogenetic response)');
plotActivations(off_leak_cell_id, psth_pattern, psth_label_opto, activation_labels, ...
    'Show_Stimulus', 'blocks', ...
    'Show_Stimulus_Block_As_Luminance', true, ...
    'Upper_Bound', up_bound, ...
    'Show_Legend', false, ...
    'PSTHS', psths, ...
    'ACTIVATIONS', activations, ...
    'Colors_Active_One', color_off);
xlim(x_lims)

subplot(3, 3, 9);
title('OFF Cell (control response)');
plotActivations(off_leak_cell_id, psth_pattern, psth_label_control, activation_labels, ...
    'Show_Stimulus', 'blocks', ...
    'Show_Stimulus_Block_As_Luminance', true, ...
    'Upper_Bound', up_bound, ...
    'Show_Legend', false, ...
    'PSTHS', psths, ...
    'ACTIVATIONS', activations, ...
    'Colors_Active_One', color_off);
xlim(x_lims)