clear
close all

exp_id = '20210302_reachr2';
mea_rate = 20000;
on_sus_cell_id = 23;
off_sus_cell_id = 1;
on_tra_cell_id = 5;
off_tra_cell_id = 30;

psth_pattern = 'euler';
activation_labels = {'on', 'off'};

psth_label_visual = 'simple';
psth_label_opto = 'lap4_acet_30nd100p';

section_id_visual = '2-euler';
section_id_opto = '29-euler_(lap4_acet_30nd100p)';
pattern_id = 1;

color_active_one = [1, 0, 0; 0, 0, 1];
x_lims = [0, 25];
up_bound = 50;

changeDataset(exp_id);
load(getDatasetMat(), 'psths', 'activations', 'cellsTable');

spike_times = getSpikeTimes(exp_id);

on_sus_cell_N = cellsTable(on_sus_cell_id).N;
off_sus_cell_N = cellsTable(off_sus_cell_id).N;
on_tra_cell_N = cellsTable(on_tra_cell_id).N;
off_tra_cell_N = cellsTable(off_tra_cell_id).N;

repetitions_visual = getRepetitions(exp_id, section_id_visual);
n_steps_visual = repetitions_visual.durations{pattern_id};
rep_begin_visual = repetitions_visual.rep_begins{pattern_id};

repetitions_opto = getRepetitions(exp_id, section_id_opto);
n_steps_opto = repetitions_opto.durations{pattern_id};
rep_begin_opto = repetitions_opto.rep_begins{pattern_id};


subplot(4, 2, 1);
title('Cell #1 (visual response)');
plotActivations(on_sus_cell_id, psth_pattern, psth_label_visual, activation_labels, ...
    'Show_Stimulus', 'trace', ...
    'Upper_Bound', up_bound, ...
    'Show_Legend', false, ...
    'PSTHS', psths, ...
    'ACTIVATIONS', activations, ...
    'Colors_Active_One', color_active_one);
xlim(x_lims)
xlabel('Time (s)');
ylabel('Firing Rate (Hz)');

subplot(4, 2, 2);
title('Cell #1 (optogenetic response)');
plotActivations(on_sus_cell_id, psth_pattern, psth_label_opto, activation_labels, ...
    'Show_Stimulus', 'trace', ...
    'Upper_Bound', up_bound, ...
    'Show_Legend', false, ...
    'PSTHS', psths, ...
    'ACTIVATIONS', activations, ...
    'Colors_Active_One', color_active_one);
xlim(x_lims)
xlabel('Time (s)');
ylabel('Firing Rate (Hz)');


subplot(4, 2, 3);
title('Cell #2 (visual response)');
plotActivations(on_tra_cell_id, psth_pattern, psth_label_visual, activation_labels, ...
    'Show_Stimulus', 'trace', ...
    'Upper_Bound', up_bound, ...
    'Show_Legend', false, ...
    'PSTHS', psths, ...
    'ACTIVATIONS', activations, ...
    'Colors_Active_One', color_active_one);
xlim(x_lims)
xlabel('Time (s)');
ylabel('Firing Rate (Hz)');

subplot(4, 2, 4);
title('Cell #2 (optogenetic response)');
plotActivations(on_tra_cell_id, psth_pattern, psth_label_opto, activation_labels, ...
    'Show_Stimulus', 'trace', ...
    'Upper_Bound', up_bound, ...
    'Show_Legend', false, ...
    'PSTHS', psths, ...
    'ACTIVATIONS', activations, ...
    'Colors_Active_One', color_active_one);
xlim(x_lims)
xlabel('Time (s)');
ylabel('Firing Rate (Hz)');




subplot(4, 2, 5);
title('Cell #3 (visual response)');
plotActivations(off_sus_cell_id, psth_pattern, psth_label_visual, activation_labels, ...
    'Show_Stimulus', 'trace', ...
    'Upper_Bound', up_bound, ...
    'Show_Legend', false, ...
    'PSTHS', psths, ...
    'ACTIVATIONS', activations, ...
    'Colors_Active_One', color_active_one);
xlim(x_lims)
xlabel('Time (s)');
ylabel('Firing Rate (Hz)');

subplot(4, 2, 6);
title('Cell #3 (optogenetic response)');
plotActivations(off_sus_cell_id, psth_pattern, psth_label_opto, activation_labels, ...
    'Show_Stimulus', 'trace', ...
    'Upper_Bound', up_bound, ...
    'Show_Legend', false, ...
    'PSTHS', psths, ...
    'ACTIVATIONS', activations, ...
    'Colors_Active_One', color_active_one);
xlim(x_lims)
xlabel('Time (s)');
ylabel('Firing Rate (Hz)');


subplot(4, 2, 7);
title('Cell #4 (visual response)');
plotActivations(off_tra_cell_id, psth_pattern, psth_label_visual, activation_labels, ...
    'Show_Stimulus', 'trace', ...
    'Upper_Bound', up_bound, ...
    'Show_Legend', false, ...
    'PSTHS', psths, ...
    'ACTIVATIONS', activations, ...
    'Colors_Active_One', color_active_one);
xlim(x_lims)
xlabel('Time (s)');
ylabel('Firing Rate (Hz)');

subplot(4, 2, 8);
title('Cell #4 (optogenetic response)');
plotActivations(off_tra_cell_id, psth_pattern, psth_label_opto, activation_labels, ...
    'Show_Stimulus', 'trace', ...
    'Upper_Bound', up_bound, ...
    'Show_Legend', false, ...
    'PSTHS', psths, ...
    'ACTIVATIONS', activations, ...
    'Colors_Active_One', color_active_one, ...
    'Color_Active_All', [0, 0, 1]);
xlim(x_lims)
xlabel('Time (s)');
ylabel('Firing Rate (Hz)');
