function plotKSTest(x1, x2)


histogram(x1(:), -0.125:0.25:3.125, ...
    'Normalization','cdf', ... 
    'DisplayStyle', 'stairs', ...
    'LineWidth', 1.5, ...
    'EdgeColor', 'r');
hold on

histogram(x2(:), -0.125:0.25:3.125, ...
    'Normalization','cdf', ... 
    'DisplayStyle', 'stairs', ...
    'LineStyle', '--', ...
    'LineWidth', 1.5, ...
    'EdgeColor', 'k');

xlabel("Normalized Nearest Neighbor Distances");
ylabel("Frequency");

ylim([0 1.1]);

title_txt = 'NNNDs';
title(title_txt)
